export const GET_SERVICES = '[API SERVICES] GET SERVICES';
export const FETCH_SERVICES = '[API SERVICES] FETCH SERVICES';

export const DELETE_SERVICE = '[API SERVICES] DELETE SERVICE';

export const INSERT_NEW_SERVICE = '[API SERVICES] INSERT NEW SERVICES';

export const EDIT_SERVICE = '[API SERVICES] EDIT SELECTED SERVICE';

export const SET_SERVICES_SEARCH_TEXT =
  '[API SERVICES] SET SERVICES SEARCH TEXT';

export const GET_SERVICES_BY_ID = '[API SERVICES] GET SERVICE BY ID';
export const FETCH_SERVICES_BY_ID = '[API SERVICES] FETCH SERVICE BY ID';

export const GET_OPERATIONS = '[API OPERATIONS] GET OPERATIONS';

export const FETCH_OPERATIONS = '[API OPERATIONS] FETCH OPERATIONS';
export const DELETE_OPERATION = '[API OPERATIONS] DELETE OPERATION';
export const INSERT_NEW_OPERATION = '[API OPERATIONS] INSERT NEW OPERATIONS';
export const EDIT_OPERATION = '[API OPERATIONS] EDIT SELECTED OPERATION';
export const SET_OPERATIONS_SEARCH_TEXT =
  '[API OPERATIONS] SET OPERATIONS SEARCH TEXT';
export const GET_OPERATION_BY_ID = '[API OPERATIONS] GET OPERATION BY ID';
export const FETCH_OPERATION_BY_ID = '[API OPERATIONS] FETCH OPERATION BY ID';

export const GET_MAPPING_BY_OPERATION = '[API OPERATIONS] GET MAPPING BY ID';
export const FETCH_MAPPING_BY_OPERATION =
  '[API OPERATIONS] FETCH MAPPING BY ID';
export const SAVE_MAPPINGS_BY_OPERATION = '[API OPERATIONS] SAVE MAPPING BY ID';
export const UPDATE_MAPPINGS_BY_OPERATION =
  '[API OPERATIONS] UPDATE MAPPING BY ID';
export const DELETE_MAPPINGS_BY_OPERATION =
  '[API OPERATIONS] DELETE MAPPING BY ID';

export const UPDATE_INPUT_OPERATION =
  '[API OPERATIONS] UPDATE DETAIL OPERATION';

export const GET_TEMPLATE_FORM = '[API OPERATIONS] GET FORM DEFINITION';
export const FETCH_TEMPLATE_FORM = '[API OPERATIONS] FETCH FORM DEFINITION';

export const GET_SERVICE_UPLOAD_FORM='GET_SERVICE_UPLOAD_FORM';
export const FETCH_SERVICE_UPLOAD_FORM='FETCH_SERVICE_UPLOAD_FORM';
export const GET_OPERATION_TESTING_START='GET_OPERATION_TESTING_START';
export const GET_OPERATION_TESTING_SUCCESS='GET_OPERATION_TESTING_SUCCESS';
export const UPDATE_TEMPLATE = '[API OPERATIONS] UPDATE TEMPLATE';
export const INSERT_TEMPLATE = '[API OPERATIONS] INSERT TEMPLATE';

export const UPDATE_MAPPING_PUBLISHED =
  '[API OPERATIONS] UPDATE MAPPING PUBLISHED';

export const GET_SERVICE_LIST_DOWNLOAD='GET_SERVICE_LIST_DOWNLOAD';
export const GET_SERVICE_LIST_UPLOAD='GET_SERVICE_LIST_UPLOAD';

export const GET_ALL_MAPPING='GET_ALL_MAPPING';
export const GET_ALL_MAPPING_SUCCESS='GET_ALL_MAPPING_SUCCESS';