export const REFRESH = {
  PROPERTY: {
    STATE_ROLE_ASSIGNMENT: '[ADMIN] [PROPERTY] [REFRESH] STATE_ROLE_ASSIGNMENT',
    LEGAL_ENTITY: '[ADMIN] [PROPERTY] [REFRESH] LEGAL_ENTITY',
    TEAM_ROLES: '[ADMIN] [PROPERTY] [REFRESH] TEAM_ROLES',
    DEFAULT_ROLES: '[ADMIN] [PROPERTY] [REFRESH] DEFAULT_ROLES'
  },
  RULES: {
    STATE_EVICTION: '[ADMIN] [RULES] [REFRESH] STATE_EVICTION',
    MANAGE_VALUVATION: '[ADMIN] [RULES] [REFRESH] MANAGE_VALUVATION',
    MANAGE_COMMISSION: '[ADMIN] [RULES] [REFRESH] MANAGE_COMMISSION'
  },
  SETTINGS: {
    MANAGE_WORKFLOW_SETTING:
      '[ADMIN] [SETTINGS] [REFRESH] MANAGE_WORKFLOW_SETTING',
    MANAGE_SET_RESERVE_PRICE:
      '[ADMIN] [SETTINGS] [REFRESH] MANAGE_SET_RESERVE_PRICE',
    MANAGE_STATE_APPRAISAL:
      '[ADMIN] [SETTINGS] [REFRESH] MANAGE_STATE_APPRAISAL'
  },
  ACCESS_MANAGMENT: {
    MI_COMPANY: '[ADMIN] [SETTINGS] [REFRESH] MI_COMPANY',
    INVESTOR: '[ADMIN] [SETTINGS] [REFRESH] INVESTOR',
    INVESTOR_GROUP: '[ADMIN] [SETTINGS] [REFRESH] INVESTOR_GROUP'
  },
  admin: (type, payload) => ({
    type,
    payload
  })
};
