export const FLOWABLE_PROCESS_DEFINITION = '[FLOWABLE] PROCESS DEFINITION';
export const FLOWABLE_GET_DEFINITION = '[FLOWABLE] GET DEFINITION';
export const FLOWABLE_QUERY_TASK = '[FLOWABLE] QUERY TASK';
export const FLOWABLE_COMPLETE_TASK = '[FLOWABLE] COMPLETE TASK';
export const FLOWABLE_FINISHED_ALL_TASKS = '[FLOWABLE] FINISHED ALL TASKS';

export const FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION =
  '[FLOWABLE] FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION';
export const FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION_FAILED =
  '[FLOWABLE] FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION_FAILED';

export const FLOWABLE_GET_CMMN_API_TASK = 'FLOWABLE_GET_CMMN_API_TASK';
export const FLOWABLE_CORE_SAVE_AND_COMPLETE_LATER =
  'FLOWABLE_CORE_SAVE_AND_COMPLETE_LATER';
export const FLOWABLE_CORE_SAVE_AND_COMPLETE_LATER_SUCCESS =
  'FLOWABLE_CORE_SAVE_AND_COMPLETE_LATER_SUCCESS';
export const FLOWABLE_CORE_API_COMPLETE_TASK =
  'FLOWABLE_CORE_API_COMPLETE_TASK';
export const FLOWABLE_CORE_API_COMPLETE_TASK_SUCCESS =
  'FLOWABLE_CORE_API_COMPLETE_TASK_SUCCESS';
export const FLOWABLE_CORE_API_SKIP_TASK_SUCCESS =
  'FLOWABLE_CORE_API_SKIP_TASK_SUCCESS';
export const FLOWABLE_CORE_API_SKIP_TASK = 'FLOWABLE_CORE_API_SKIP_TASK';

export const FLOWABLE_CORE_API_UNCLAIM_TASK = 'FLOWABLE_CORE_API_UNCLAIM_TASK';
export const FLOWABLE_CORE_API_UNCLAIM_TASK_SUCCESS =
  'FLOWABLE_CORE_API_UNCLAIM_TASK_SUCCESS';
export const FLOWABLE_CORE_API_UNCLAIM_TASK_RESET =
  'FLOWABLE_CORE_API_UNCLAIM_TASK_RESET';
export const FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION_LOCAL =
  '[FLOWABLE_LOCAL] FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION';
export const FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION_LOCAL_FAILED =
  '[FLOWABLE_LOCAL] FLOWABLE_GET_FORM_BY_PROCESS_DEFINITION_LOCAL_FAILED';
export const RESET_FLOWABLE_PROCESS_STATE_START =
  'RESET_FLOWABLE_PROCESS_STATE_START';
export const RESET_FLOWABLE_PROCESS_STATE_SUCCESS =
  'RESET_FLOWABLE_PROCESS_STATE_SUCCESS';

export const FLOWABLE_PROCESS_GET_EXECUTIONS_START =
  'FLOWABLE_PROCESS_GET_EXECUTIONS_START';
export const FLOWABLE_PROCESS_GET_EXECUTIONS_SUCCESS =
  'FLOWABLE_PROCESS_GET_EXECUTIONS_SUCCESS';

export const FLOWABLE_PROCESS_GET_EXECUTION_BY_ID_START =
  'FLOWABLE_PROCESS_GET_EXECUTION_BY_ID_START';
export const FLOWABLE_PROCESS_GET_EXECUTION_BY_ID_SUCCESS =
  'FLOWABLE_PROCESS_GET_EXECUTION_BY_ID_SUCCESS';

export const FLOWABLE_TRIGGER_EVENT_BY_EXECUTION_ID_START =
  'FLOWABLE_TRIGGER_EVENT_BY_EXECUTION_ID_START';
export const FLOWABLE_TRIGGER_EVENT_BY_EXECUTION_ID_SUCCESS =
  'FLOWABLE_TRIGGER_EVENT_BY_EXECUTION_ID_SUCCESS';

export const FLOWABLE_PROCESS_DEFINITION_BY_JSON =
  'FLOWABLE_PROCESS_DEFINITION_BY_JSON';
export const FLOWABLE_DATA_DEFINITION_BY_JSON =
  'FLOWABLE_GET_DEFINITION_BY_JSON';
export const FLOWABLE_DEFINITION_BY_JSON_CLEAR =
  'FLOWABLE_DEFINITION_BY_JSON_CLEAR';

export const FLOWABLE_PROCESS_TASK_DEFINITION =
  'FLOWABLE_PROCESS_TASK_DEFINITION';

export const FLOWABLE_PROCESS_TASK_FORM_PAYLOAD =
  'FLOWABLE_PROCESS_TASK_FORM_PAYLOAD';

export const FLOWABLE_PROCESS_TASK_FORM_PAYLOAD_VARIABLES =
  'FLOWABLE_PROCESS_TASK_FORM_PAYLOAD_VARIABLES';

export const FLOWABLE_GET_FORM_BY_CASE_DEFINITION_ID =
  '[FLOWABLE_LOCAL] FLOWABLE_GET_FORM_BY_CASE_DEFINITION_ID';
export const FLOWABLE_GET_FORM_BY_CASE_DEFINITION_ID_FAILED =
  '[FLOWABLE_LOCAL] FLOWABLE_GET_FORM_BY_CASE_DEFINITION_ID_FAILED';

export const FLOWABLE_CORE_API_PAUSE_TASK = 'FLOWABLE_CORE_API_PAUSE_TASK';
export const FLOWABLE_CORE_API_PAUSE_TASK_SUCCESS =
  'FLOWABLE_CORE_API_PAUSE_TASK_SUCCESS';
export const FLOWABLE_CORE_API_UNPAUSE_TASK_SUCCESS =
  'FLOWABLE_CORE_API_UNPAUSE_TASK_SUCCESS';
export const FLOWABLE_CORE_API_UNPAUSE_TASK = 'FLOWABLE_CORE_API_UNPAUSE_TASK';
export const FLOWABLE_TASK_PAUSE_UNPAUSE_INITIAL_CALL =
  'FLOWABLE_TASK_PAUSE_UNPAUSE_INITIAL_CALL';
