export const RESOURCE_ADD_START = 'RESOURCE_ADD_START';
export const USER_ADD_START = 'USER_ADD_START';
export const ROLE_ADD_START = 'ROLE_ADD_START';
export const GROUP_ADD_START = 'GROUP_ADD_START';

export const RESOURCE_VIEW_START = 'RESOURCE_VIEW_START';
export const RESOURCE_EDIT_START = 'RESOURCE_EDIT_START';
export const RESOURCE_EDIT_SUCCESS = 'RESOURCE_EDIT_SUCCESS';

export const USER_VIEW_START = 'USER_VIEW_START';
export const USER_EDIT_START = 'USER_EDIT_START';
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS';

export const ROLE_VIEW_START = 'ROLE_VIEW_START';
export const ROLE_EDIT_START = 'ROLE_EDIT_START';
export const ROLE_EDIT_SUCCESS = 'ROLE_EDIT_SUCCESS';
export const ROLE_VIEW_SUCCESS = 'ROLE_VIEW_SUCCESS';

export const GROUP_VIEW_START = 'GROUP_VIEW_START';
export const GROUP_EDIT_START = 'GROUP_EDIT_START';
export const GROUP_EDIT_SUCCESS = 'GROUP_EDIT_SUCCESS';
export const GROUP_EDIT_DATA = 'GROUP_EDIT_DATA';

export const USER_DELETE_START = 'USER_DELETE_START';
export const GROUP_DELETE_START = 'GROUP_DELETE_START';
export const RESOURCE_DELETE_START = 'RESOURCE_DELETE_START';
export const ROLE_DELETE_START = 'ROLE_DELETE_START';
export const ROLE_DELETE_START_SUCCESS = 'ROLE_DELETE_START_SUCCESS';
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS';
export const RESOURCE_DELETE_SUCCESS = 'RESOURCE_DELETE_SUCCESS';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

export const USER_LISTING_FORM_FETCH_START = 'USER_LISTING_FORM_FETCH_START';
export const USER_LISTING_FORM_FETCH_SUCCESS =
  'USER_LISTING_FORM_FETCH_SUCCESS';

export const GROUP_LISTING_FORM_FETCH_START = 'GROUP_LISTING_FORM_FETCH_START';
export const GROUP_LISTING_FORM_FETCH_SUCCESS =
  'GROUP_LISTING_FORM_FETCH_SUCCESS';

export const RESOURCE_LISTING_FORM_FETCH_START =
  'RESOURCE_LISTING_FORM_FETCH_START';
export const RESOURCE_LISTING_FORM_FETCH_SUCCESS =
  'RESOURCE_LISTING_FORM_FETCH_SUCCESS';

export const ROLE_LISTING_FORM_FETCH_START = 'ROLE_LISTING_FORM_FETCH_START';
export const ROLE_LISTING_FORM_FETCH_SUCCESS =
  'ROLE_LISTING_FORM_FETCH_SUCCESS';

export const GROUP_ADD_FORM_FETCH_START = 'GROUP_ADD_FORM_FETCH_START';
export const USER_ADD_FORM_FETCH_START = 'USER_ADD_FORM_FETCH_START';
export const RESOURCE_ADD_FORM_FETCH_START = 'RESOURCE_ADD_FORM_FETCH_START';
export const ROLE_ADD_FORM_FETCH_START = 'ROLE_ADD_FORM_FETCH_START';

export const GROUP_ADD_FORM_FETCH_SUCCESS = 'GROUP_ADD_FORM_FETCH_SUCCESS';
export const USER_ADD_FORM_FETCH_SUCCESS = 'USER_ADD_FORM_FETCH_SUCCESS';
export const RESOURCE_ADD_FORM_FETCH_SUCCESS =
  'RESOURCE_ADD_FORM_FETCH_SUCCESS';
export const ROLE_ADD_FORM_FETCH_SUCCESS = 'ROLE_ADD_FORM_FETCH_SUCCESS';

export const GROUP_ADD_START_FAILURE = 'GROUP_ADD_START_FAILURE';
export const USER_ADD_START_FAILURE = 'USER_ADD_START_FAILURE';
export const RESOURCE_ADD_START_FAILURE = 'RESOURCE_ADD_START_FAILURE';
export const ROLE_ADD_START_FAILURE = 'ROLE_ADD_START_FAILURE';

export const USER_VIEW_START_FAILURE = 'USER_VIEW_START_FAILURE';
export const GROUP_VIEW_START_FAILURE = 'GROUP_VIEW_START_FAILURE';
export const RESOURCE_VIEW_START_FAILURE = 'RESOURCE_VIEW_START_FAILURE';
export const ROLE_VIEW_START_FAILURE = 'ROLE_VIEW_START_FAILURE';

export const USER_EDIT_START_FAILURE = 'USER_EDIT_START_FAILURE';
export const GROUP_EDIT_START_FAILURE = 'GROUP_EDIT_START_FAILURE';
export const RESOURCE_EDIT_START_FAILURE = 'RESOURCE_EDIT_START_FAILURE';
export const ROLE_EDIT_START_FAILURE = 'ROLE_EDIT_START_FAILURE';

export const USER_DELETE_START_FAILURE = 'USER_DELETE_START_FAILURE';
export const GROUP_DELETE_START_FAILURE = 'GROUP_DELETE_START_FAILURE';
export const RESOURCE_DELETE_START_FAILURE = 'RESOURCE_DELETE_START_FAILURE';
export const ROLE_DELETE_START_FAILURE = 'ROLE_DELETE_START_FAILURE';

export const TENANT_TABS_UPDATE_START = 'TENANT_TABS_UPDATE_START';
export const TENANT_TABS_UPDATE_SUCCESS = 'TENANT_TABS_UPDATE_SUCCESS';

export const TENANT_ADD_START = 'TENANT_ADD_START';
export const TENANT_ADD_SUCCESS = 'TENANT_ADD_SUCCESS';

export const TENANT_ADD_FORM_FETCH_START = 'TENANT_ADD_FORM_FETCH_START';
export const TENANT_ADD_FORM_FETCH_SUCCESS = 'TENANT_ADD_FORM_FETCH_SUCCESS';

export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS';
export const TENANT_EDIT_START = 'TENANT_EDIT_START';
export const TENANT_EDIT_SUCCESS = 'TENANT_EDIT_SUCCESS';

export const TENANT_HEADER_FORM_FETCH_START = 'TENANT_HEADER_FORM_FETCH_START';
export const TENANT_HEADER_FORM_FETCH_SUCCESS =
  'TENANT_HEADER_FORM_FETCH_SUCCESS';
export const TENANT_HEADER_FORM_FETCH_FAILURE =
  'TENANT_HEADER_FORM_FETCH_FAILURE';

export const ROLE_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';
export const RESOURCE_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';
export const GROUP_ADD_SUCCESS = 'ROLE_ADD_SUCCESS';

export const TENANT_GET_START = 'TENANT_GET_START';
export const TENANT_GET_SUCCESS = 'TENANT_GET_SUCCESS';

export const TENANT_LIST_FORM_FETCH_START = 'TENANT_LIST_FORM_FETCH_START';
export const TENANT_LIST_FORM_FETCH_SUCCESS = 'TENANT_LIST_FORM_FETCH_SUCCESS';

export const RESOURCE_UPLOAD_FILE = 'RESOURCE_UPLOAD_FILE';
export const RESOURCE_DOWNLOAD_FILE = 'RESOURCE_DOWNLOAD_FILE';
export const RESOURCE_MODAL_CLOSE = 'RESOURCE_MODAL_CLOSE';
export const RESOURCE_LIST_REFRESH_TIME = 'RESOURCE_LIST_REFRESH_TIME';
export const RESOURCE_SINK_START = 'RESOURCE_SINK_START';

export const USER_ROLE_GROUP_ADD = 'USER_ROLE_GROUP_ADD';
export const USER_ADD_RESPONSE = 'USER_ADD_RESPONSE';
export const GET_USER_UID_START = 'GET_USER_UID_START';
export const GET_USER_UID_SUCCESS = 'GET_USER_UID_SUCCESS';
export const GET_USER_UID_FAIL = 'GET_USER_UID_FAIL';
export const USER_ACCESS_TAB = 'USER_ACCESS_TAB';

export const TENANT_ROLE_FETCH_START = 'TENANT_ROLE_FETCH_START';
export const TENANT_ROLE_FETCH_SUCCESS = 'TENANT_ROLE_FETCH_SUCCESS';
export const TENANT_ROLE_FETCH_FAILURE = 'TENANT_ROLE_FETCH_FAILURE';
export const TENANT_RESOURCE_FETCH_START = 'TENANT_RESOURCE_FETCH_START';
export const TENANT_RESOURCE_FETCH_SUCCESS = 'TENANT_RESOURCE_FETCH_SUCCESS';
export const TENANT_RESOURCE_FETCH_FAILURE = 'TENANT_RESOURCE_FETCH_FAILURE';
export const TENANT_ROLE_PRIVILEGE_DATA_FOR_EDIT_START =
  'TENANT_ROLE_PRIVILEGE_DATA_FOR_EDIT_START';
export const TENANT_ROLE_PRIVILEGE_DATA_FOR_EDIT_SUCCESS =
  'TENANT_ROLE_PRIVILEGE_DATA_FOR_EDIT_SUCCESS';
export const TENANT_ROLE_PRIVILEGE_DATA_FOR_EDIT_FAILURE =
  'TENANT_ROLE_PRIVILEGE_DATA_FOR_EDIT_FAILURE';
export const TENANT_ROLE_PRIVILEGE_SAVE_START =
  'TENANT_ROLE_PRIVILEGE_SAVE_START';
export const TENANT_ROLE_PRIVILEGE_SAVE_SUCCESS =
  'TENANT_ROLE_PRIVILEGE_SAVE_SUCCESS';
export const TENANT_ROLE_PRIVILEGE_SAVE_FAILURE =
  'TENANT_ROLE_PRIVILEGE_SAVE_FAILURE';
export const USER_CANCEL_BUTTON = 'USER_CANCEL_BUTTON';

export const TENANT_FETCH_START = 'TENANT_FETCH_START';
export const TENANT_FETCH_SUCCESS = 'TENANT_FETCH_SUCCESS';
export const TENANT_FETCH_FAILURE = 'TENANT_FETCH_FAILURE';

export const DATA_MASK_ADD_START = 'DATA_MASK_ADD_START';
export const DATA_MASK_ADD_SUCCESS = 'DATA_MASK_ADD_SUCCESS';
export const DATA_MASK_ADD_FAILURE = 'DATA_MASK_ADD_FAILURE';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const USER_LIST_ROW_DATA = 'USER_LIST_ROW_DATA';

export const TENANT_PROPERTY_ROLES_ADD_START =
  'TENANT_PROPERTY_ROLES_ADD_START';
export const TENANT_PROPERTY_ROLES_ADD_SUCCESS =
  'TENANT_PROPERTY_ROLES_ADD_SUCCESS';
export const TENANT_ADD_EDIT_PROPERTY_ROLE_FORM_DATA =
  'TENANT_ADD_EDIT_PROPERTY_ROLE_FORM_DATA';
export const TENANT_PROPERTY_ROLES_DELETE_START =
  'TENANT_PROPERTY_ROLES_DELETE_START';
export const TENANT_PROPERTY_ROLES_USERS_START =
  'TENANT_PROPERTY_ROLES_USERS_START';
export const TENANT_PROPERTY_ROLES_USERS_SUCCESS =
  'TENANT_PROPERTY_ROLES_USERS_SUCCESS';
export const TENANT_PROPERTY_ROLES_TABLE_REFRESH =
  'TENANT_PROPERTY_ROLES_TABLE_REFRESH';
export const GET_TENANT_PROPERTY_ROLES_START =
  'GET_TENANT_PROPERTY_ROLES_START';
export const GET_TENANT_PROPERTY_ROLES_SUCCESS =
  'GET_TENANT_PROPERTY_ROLES_SUCCESS';
export const TENANT_FORMDEFIINITION='TENANT_FORMDEFIINITION'  
export const RESOURCE_UPLOAD_FILE_SUCCESS='RESOURCE_UPLOAD_FILE_SUCCESS'  
