export const GET_MAIL_COMPOSE_FORM = '[MAIL APP] GET FLOWABLE FORM DETAIL';
export const FETCH_MAIL_COMPOSE_FORM = '[MAIL APP] FETCH FLOWABLE FORM DATA';

export const POST_MAIL_COMPOSE_DATA = '[MAIL APP] POST_COMPOSE_DATA';
export const GET_MAIL_COMPOSE_DATA = '[MAIL APP] GET_COMPOSE_DATA';

export const FETCH_MAILS = '[MAIL APP] FETCH_MAILS';
export const FETCH_MAIL_BY_ID = '[MAIL APP] FETCH_MAILS BY ID';

export const GET_MAIL = '[MAIL APP] GET MAIL';
export const UPDATE_MAIL = '[MAIL APP] UPDATE MAIL';
export const UPDATE_MAIL_BY_ID = '[MAIL APP] UPDATE MAIL BY ID';
export const TOGGLE_STAR = '[MAIL APP] TOGGLE STAR MAIL';
export const TOGGLE_IMPORTANT = '[MAIL APP] TOGGLE IMPORTANT MAIL';

export const GET_MAILS = '[MAIL APP] GET MAILS';
export const GET_MAIL_BY_ID = '[MAIL APP] GET MAIL BY ID';
export const UPDATE_MAILS = '[MAIL APP] UPDATE MAILS';
export const SELECT_ALL_MAILS = '[MAILS] SELECT ALL MAILS';
export const DESELECT_ALL_MAILS = '[MAILS] DESELECT ALL MAILS';
export const TOGGLE_IN_SELECTED_MAILS = '[MAILS] TOGGLE IN SELECTED MAILS';
export const SELECT_MAILS_BY_PARAMETER = '[MAILS] SELECT MAILS BY PARAMETER';
export const SET_FOLDER_ON_SELECTED_MAILS =
  '[MAILS] SET FOLDER ON SELECTED MAILS';
export const TOGGLE_LABEL_ON_SELECTED_MAILS =
  '[MAILS] TOGGLE LABEL ON SELECTED MAILS';
export const SET_SEARCH_TEXT = '[MAILS] SET SEARCH TEXT';
export const FETCH_MAILS_UNREAD_COUNT = '[MAILS] FETCH MAILS UNREAD COUNT';
export const GET_MAILS_UNREAD_COUNT = '[MAILS] GET MAILS UNREAD COUNT';
export const NAV_GO_BACK_START = 'NAV_GO_BACK_START';
export const NAV_GO_BACK_END = 'NAV_GO_BACK_END';
export const MAIL_FORMDEFIINITION = 'MAIL_FORMDEFIINITION';
export const MAIL_TABLE_ROW_SELECT = 'MAIL_TABLE_ROW_SELECT';
export const RESET_MAIL = 'RESET_MAIL';
