export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';
export const REST_API_MESSAGES = 'REST_API_MESSAGES';

export const POST_UPLOAD_ATTACHMENT = '[FILE UPLOAD] POST_ATTACHMENT';
export const GET_UPLOAD_ATTACHMENT = '[FILE UPLOAD] GET_ATTACHMENT';
export const FINISHED_UPLOAD = '[FILE UPLOAD] FINISHED_UPLOAD';
export const RESET_UPLOAD = '[FILE UPLOAD] RESET_UPLOAD';

export const NAVIGATION_START = 'NAVIGATION_START';
export const NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS';
export const NAVIGATION_FAILURE = 'NAVIGATION_FAILURE';

export const RESET_UPLOAD_FILE = 'RESET_UPLOAD_FILE';

export const EXPLORE_TOUR_START = 'EXPLORE_TOUR_START';
export const EXPLORE_TOUR_SUCCESS = 'EXPLORE_TOUR_SUCCESS';

export const FLOWABLE_FORM_REFRESH_START = 'FLOWABLE_FORM_REFRESH_START';
export const FLOWABLE_FORM_REFRESH_SUCCESS = 'FLOWABLE_FORM_REFRESH_SUCCESS';
