export const PROPERTY_TABS_UPDATE_START = 'PROPERTY_TABS_UPDATE_START';
export const PROPERTY_TABS_UPDATE_SUCCESS = 'PROPERTY_TABS_UPDATE_SUCCESS';
export const PROPERTY_TABS_UPDATE_FAILURE = 'PROPERTY_TABS_UPDATE_FAILURE';

export const PROPERTY_NAVIGATION_START = 'PROPERTY_NAVIGATION_START';
export const PROPERTY_NAVIGATION_SUCCESS = 'PROPERTY_NAVIGATION_SUCCESS';
export const PROPERTY_NAVIGATION_FAILURE = 'PROPERTY_NAVIGATION_FAILURE';

export const PROPERTY_FETCH_START = 'PROPERTY_FETCH_START';
export const PROPERTY_FETCH_SUCCESS = 'PROPERTY_FETCH_SUCCESS';
export const PROPERTY_FETCH_FAILURE = 'PROPERTY_FETCH_FAILURE';

export const PROPERTY_ADD_START = 'PROPERTY_ADD_START';
export const PROPERTY_ADD_SUCCESS = 'PROPERTY_ADD_SUCCESS';
export const PROPERTY_ADD_FAILURE = 'PROPERTY_ADD_FAILURE';

export const PROPERTY_UPDATE_START = 'PROPERTY_UPDATE_START';
export const PROPERTY_UPDATE_SUCCESS = 'PROPERTY_UPDATE_SUCCESS';
export const PROPERTY_UPDATE_FAILURE = 'PROPERTY_UPDATE_FAILURE';

export const PROPERTY_ADD_FORM_FETCH_START = 'PROPERTY_ADD_FORM_FETCH_START';
export const PROPERTY_ADD_FORM_FETCH_SUCCESS =
  'PROPERTY_ADD_FORM_FETCH_SUCCESS';
export const PROPERTY_ADD_FORM_FETCH_FAILURE =
  'PROPERTY_ADD_FORM_FETCH_FAILURE';

export const PROPERTY_UPDATE_FORM_FETCH_START =
  'PROPERTY_UPDATE_FORM_FETCH_START';
export const PROPERTY_UPDATE_FORM_FETCH_SUCCESS =
  'PROPERTY_UPDATE_FORM_FETCH_SUCCESS';
export const PROPERTY_UPDATE_FORM_FETCH_FAILURE =
  'PROPERTY_UPDATE_FORM_FETCH_FAILURE';

export const PROPERTY_LISTING_FORM_FETCH_FAILURE =
  'PROPERTY_LISTING_FORM_FETCH_FAILURE';

export const PROPERTY_HEADER_FORM_FETCH_START =
  'PROPERTY_HEADER_FORM_FETCH_START';
export const PROPERTY_HEADER_FORM_FETCH_SUCCESS =
  'PROPERTY_HEADER_FORM_FETCH_SUCCESS';
export const PROPERTY_HEADER_FORM_FETCH_FAILURE =
  'PROPERTY_HEADER_FORM_FETCH_FAILURE';

export const PROPERTY_TASK_LISTING_FORM_FETCH_START =
  'PROPERTY_TASK_LISTING_FORM_FETCH_START';
export const PROPERTY_TASK_LISTING_FORM_FETCH_SUCCESS =
  'PROPERTY_TASK_LISTING_FORM_FETCH_SUCCESS';
export const PROPERTY_TASK_LISTING_FORM_FETCH_FAILURE =
  'PROPERTY_TASK_LISTING_FORM_FETCH_FAILURE';

export const PROPERTY_TASK_DETAILS_FETCH_START =
  'PROPERTY_TASK_DETAILS_FETCH_START';
export const PROPERTY_TASK_DETAILS_FETCH_SUCCESS =
  'PROPERTY_TASK_DETAILS_FETCH_SUCCESS';
export const PROPERTY_TASK_DETAILS_FETCH_FAILURE =
  'PROPERTY_TASK_DETAILS_FETCH_FAILURE';

export const PROPERTY_TASK_OPEN_FORM_FETCH_START =
  'PROPERTY_TASK_OPEN_FORM_FETCH_START';
export const PROPERTY_TASK_OPEN_FORM_FETCH_SUCCESS =
  'PROPERTY_TASK_OPEN_FORM_FETCH_SUCCESS';
export const PROPERTY_TASK_OPEN_FORM_FETCH_FAILURE =
  'PROPERTY_TASK_OPEN_FORM_FETCH_FAILURE';

export const PROPERTY_TASK_CLOSE_FORM_FETCH_START =
  'PROPERTY_TASK_CLOSE_FORM_FETCH_START';
export const PROPERTY_TASK_CLOSE_FORM_FETCH_SUCCESS =
  'PROPERTY_TASK_CLOSE_FORM_FETCH_SUCCESS';
export const PROPERTY_TASK_CLOSE_FORM_FETCH_FAILURE =
  'PROPERTY_TASK_CLOSE_FORM_FETCH_FAILURE';

export const PROPERTY_TASK_FORM_VALUE_FETCH_START =
  'PROPERTY_TASK_FORM_VALUE_FETCH_START';
export const PROPERTY_TASK_FORM_VALUE_FETCH_SUCCESS =
  'PROPERTY_TASK_FORM_VALUE_FETCH_SUCCESS';
export const PROPERTY_TASK_FORM_VALUE_FETCH_FAILURE =
  'PROPERTY_TASK_FORM_VALUE_FETCH_FAILURE';

export const PROPERTY_TASK_UPDATE_START = 'PROPERTY_TASK_UPDATE_START';
export const PROPERTY_TASK_UPDATE_SUCCESS = 'PROPERTY_TASK_UPDATE_SUCCESS';
export const PROPERTY_TASK_UPDATE_FAILURE = 'PROPERTY_TASK_UPDATE_FAILURE';

export const PROPERTY_TASK_OPEN_INSTANCE_DIAGRAM_FETCH_START =
  'PROPERTY_TASK_OPEN_INSTANCE_DIAGRAM_FETCH_START';
export const PROPERTY_TASK_OPEN_INSTANCE_DIAGRAM_FETCH_SUCCESS =
  'PROPERTY_TASK_OPEN_INSTANCE_DIAGRAM_FETCH_SUCCESS';
export const PROPERTY_TASK_OPEN_INSTANCE_DIAGRAM_FETCH_FAILURE =
  'PROPERTY_TASK_OPEN_INSTANCE_DIAGRAM_FETCH_FAILURE';

export const PROPERTY_TASK_CLOSE_INSTANCE_DIAGRAM_FETCH_START =
  'PROPERTY_TASK_CLOSE_INSTANCE_DIAGRAM_FETCH_START';
export const PROPERTY_TASK_CLOSE_INSTANCE_DIAGRAM_FETCH_SUCCESS =
  'PROPERTY_TASK_CLOSE_INSTANCE_DIAGRAM_FETCH_SUCCESS';
export const PROPERTY_TASK_CLOSE_INSTANCE_DIAGRAM_FETCH_FAILURE =
  'PROPERTY_TASK_CLOSE_INSTANCE_DIAGRAM_FETCH_FAILURE';

export const PROPERTY_TASK_INSTANCE_DIAGRAM_URL_FETCH_START =
  'PROPERTY_TASK_INSTANCE_DIAGRAM_URL_FETCH_START';
export const PROPERTY_TASK_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS =
  'PROPERTY_TASK_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS';
export const PROPERTY_TASK_INSTANCE_DIAGRAM_URL_FETCH_FAILURE =
  'PROPERTY_TASK_INSTANCE_DIAGRAM_URL_FETCH_FAILURE';

export const PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_FETCH_START =
  'PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_FETCH_START';
export const PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_FETCH_SUCCESS =
  'PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_FETCH_SUCCESS';
export const PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_FETCH_FAILURE =
  'PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_FETCH_FAILURE';

export const PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_URL_FETCH_START =
  'PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_URL_FETCH_START';
export const PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS =
  'PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS';
export const PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_URL_FETCH_FAILURE =
  'PROPERTY_TASK_PARENT_INSTANCE_DIAGRAM_URL_FETCH_FAILURE';

export const PROPERTY_TASK_ROOT_PARENT_INSTANCE_FETCH_START =
  'PROPERTY_TASK_ROOT_PARENT_INSTANCE_FETCH_START';
export const PROPERTY_TASK_ROOT_PARENT_INSTANCE_FETCH_SUCCESS =
  'PROPERTY_TASK_ROOT_PARENT_INSTANCE_FETCH_SUCCESS';
export const PROPERTY_TASK_ROOT_PARENT_INSTANCE_FETCH_FAILURE =
  'PROPERTY_TASK_ROOT_PARENT_INSTANCE_FETCH_FAILURE';

export const PROPERTY_INSTANCE_DETAILS_FETCH_START =
  'PROPERTY_INSTANCE_DETAILS_FETCH_START';
export const PROPERTY_INSTANCE_DETAILS_FETCH_SUCCESS =
  'PROPERTY_INSTANCE_DETAILS_FETCH_SUCCESS';
export const PROPERTY_INSTANCE_DETAILS_FETCH_FAILURE =
  'PROPERTY_INSTANCE_DETAILS_FETCH_FAILURE';

export const PROPERTY_INSTANCE_DIAGRAM_FETCH_START =
  'PROPERTY_INSTANCE_DIAGRAM_FETCH_START';
export const PROPERTY_INSTANCE_DIAGRAM_FETCH_SUCCESS =
  'PROPERTY_INSTANCE_DIAGRAM_FETCH_SUCCESS';
export const PROPERTY_INSTANCE_DIAGRAM_FETCH_FAILURE =
  'PROPERTY_INSTANCE_DIAGRAM_FETCH_FAILURE';

export const PROPERTY_INSTANCE_DIAGRAM_URL_FETCH_START =
  'PROPERTY_INSTANCE_DIAGRAM_URL_FETCH_START';
export const PROPERTY_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS =
  'PROPERTY_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS';
export const PROPERTY_INSTANCE_DIAGRAM_URL_FETCH_FAILURE =
  'PROPERTY_INSTANCE_DIAGRAM_URL_FETCH_FAILURE';

export const PROPERTY_PARENT_INSTANCE_DIAGRAM_URL_FETCH_START =
  'PROPERTY_PARENT_INSTANCE_DIAGRAM_URL_FETCH_START';
export const PROPERTY_PARENT_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS =
  'PROPERTY_PARENT_INSTANCE_DIAGRAM_URL_FETCH_SUCCESS';
export const PROPERTY_PARENT_INSTANCE_DIAGRAM_URL_FETCH_FAILURE =
  'PROPERTY_PARENT_INSTANCE_DIAGRAM_URL_FETCH_FAILURE';

export const PROPERTY_DOCUMENT_FORM_FETCH_START =
  'PROPERTY_DOCUMENT_FORM_FETCH_START';
export const PROPERTY_DOCUMENT_FORM_FETCH_SUCCESS =
  'PROPERTY_DOCUMENT_FORM_FETCH_SUCCESS';
export const PROPERTY_DOCUMENT_FORM_FETCH_FAILURE =
  'PROPERTY_DOCUMENT_FORM_FETCH_FAILURE';

export const PROPERTY_DOCUMENT_DELETE_START = 'PROPERTY_DOCUMENT_DELETE_START';
export const PROPERTY_DOCUMENT_DELETE_SUCCESS =
  'PROPERTY_DOCUMENT_DELETE_SUCCESS';
export const PROPERTY_DOCUMENT_DELETE_FAILURE =
  'PROPERTY_DOCUMENT_DELETE_FAILURE';

export const PROPERTY_DOCUMENT_UPLOAD_START = 'PROPERTY_DOCUMENT_UPLOAD_START';
export const PROPERTY_DOCUMENT_UPLOAD_SUCCESS =
  'PROPERTY_DOCUMENT_UPLOAD_SUCCESS';
export const PROPERTY_DOCUMENT_UPLOAD_FAILURE =
  'PROPERTY_DOCUMENT_UPLOAD_FAILURE';

export const PROPERTY_DOCUMENT_DOWNLOAD_START =
  'PROPERTY_DOCUMENT_DOWNLOAD_START';
export const PROPERTY_DOCUMENT_DOWNLOAD_SUCCESS =
  'PROPERTY_DOCUMENT_DOWNLOAD_SUCCESS';
export const PROPERTY_DOCUMENT_DOWNLOAD_FAILURE =
  'PROPERTY_DOCUMENT_DOWNLOAD_FAILURE';

export const PROPERTY_DOCUMENT_TAB_RELOAD_START =
  'PROPERTY_DOCUMENT_TAB_RELOAD_START';
export const PROPERTY_DOCUMENT_TAB_RELOAD_SUCCESS =
  'PROPERTY_DOCUMENT_TAB_RELOAD_SUCCESS';

export const PROPERTY_DECISION_LISTING_FORM_FETCH_START =
  'PROPERTY_DECISION_LISTING_FORM_FETCH_START';
export const PROPERTY_DECISION_LISTING_FORM_FETCH_SUCCESS =
  'PROPERTY_DECISION_LISTING_FORM_FETCH_SUCCESS';
export const PROPERTY_DECISION_LISTING_FORM_FETCH_FAILURE =
  'PROPERTY_DECISION_LISTING_FORM_FETCH_FAILURE';

export const PROPERTY_DECISIONS_FETCH_START = 'PROPERTY_DECISIONS_FETCH_START';
export const PROPERTY_DECISIONS_FETCH_SUCCESS =
  'PROPERTY_DECISIONS_FETCH_SUCCESS';
export const PROPERTY_DECISIONS_FETCH_FAILURE =
  'PROPERTY_DECISIONS_FETCH_FAILURE';

export const PROPERTY_DECISION_GUIDANCES_FETCH_START =
  'PROPERTY_DECISION_GUIDANCES_FETCH_START';
export const PROPERTY_DECISION_GUIDANCES_FETCH_SUCCESS =
  'PROPERTY_DECISION_GUIDANCES_FETCH_SUCCESS';
export const PROPERTY_DECISION_GUIDANCES_FETCH_FAILURE =
  'PROPERTY_DECISION_GUIDANCES_FETCH_FAILURE';

export const PROPERTY_DECISION_STATUSES_FETCH_START =
  'PROPERTY_DECISION_STATUSES_FETCH_START';
export const PROPERTY_DECISION_STATUSES_FETCH_SUCCESS =
  'PROPERTY_DECISION_STATUSES_FETCH_SUCCESS';
export const PROPERTY_DECISION_STATUSES_FETCH_FAILURE =
  'PROPERTY_DECISION_STATUSES_FETCH_FAILURE';

export const PROPERTY_DECISION_RESULTS_FETCH_START =
  'PROPERTY_DECISION_RESULTS_FETCH_START';
export const PROPERTY_DECISION_RESULTS_FETCH_SUCCESS =
  'PROPERTY_DECISION_RESULTS_FETCH_SUCCESS';
export const PROPERTY_DECISION_RESULTS_FETCH_FAILURE =
  'PROPERTY_DECISION_RESULTS_FETCH_FAILURE';

export const PROPERTY_INIT_FETCH_START = 'PROPERTY_INIT_FETCH_START';
export const PROPERTY_INIT_FETCH_SUCCESS = 'PROPERTY_INIT_FETCH_SUCCESS';
export const PROPERTY_INIT_FETCH_FAILURE = 'PROPERTY_INIT_FETCH_FAILURE';

export const PROPERTY_STAGE_OVERVIEW_FETCH_START =
  'PROPERTY_STAGE_OVERVIEW_FETCH_START';
export const PROPERTY_STAGE_OVERVIEW_FETCH_SUCCESS =
  'PROPERTY_STAGE_OVERVIEW_FETCH_SUCCESS';
export const PROPERTY_STAGE_OVERVIEW_FETCH_FAILURE =
  'PROPERTY_STAGE_OVERVIEW_FETCH_FAILURE';

export const PROPERTY_CASE_DEFINITION_FETCH_START =
  'PROPERTY_CASE_DEFINITION_FETCH_START';
export const PROPERTY_CASE_DEFINITION_FETCH_SUCCESS =
  'PROPERTY_CASE_DEFINITION_FETCH_SUCCESS';
export const PROPERTY_CASE_DEFINITION_FETCH_FAILURE =
  'PROPERTY_CASE_DEFINITION_FETCH_FAILURE';

export const PROPERTY_MILESTONE_FETCH_START = 'PROPERTY_MILESTONE_FETCH_START';
export const PROPERTY_MILESTONE_FETCH_SUCCESS =
  'PROPERTY_MILESTONE_FETCH_SUCCESS';
export const PROPERTY_MILESTONE_FETCH_FAILURE =
  'PROPERTY_MILESTONE_FETCH_FAILURE';

export const PROPERTY_CUSTOM_TASK_OPEN_LOGIC_SUCCESS =
  'PROPERTY_CUSTOM_TASK_OPEN_LOGIC_SUCCESS';

export const FETCH_LIST_OF_PROPERTIES = 'FETCH_LIST_OF_PROPERTIES';
export const GET_LIST_OF_PROPERTIES = 'GET_LIST_OF_PROPERTIES';

export const ASSIGNED_USER_ROLE_FORM_FETCH_START =
  'ASSIGNED_USER_ROLE_FORM_FETCH_START';
export const ASSIGNED_USER_ROLE_FORM_FETCH_SUCCESS =
  'ASSIGNED_USER_ROLE_FORM_FETCH_SUCCESS';
export const ASSIGNED_USER_ROLE_FORM_FETCH_FAILURE =
  'ASSIGNED_USER_ROLE_FORM_FETCH_FAILURE';

export const USER_ROLE_FETCH_START = 'USER_ROLE_FETCH_START';
export const USER_ROLE_FETCH_SUCCESS = 'USER_ROLE_FETCH_SUCCESS';
export const USER_ROLE_FETCH_FAILURE = 'USER_ROLE_FETCH_FAILURE';

export const USER_ROLE_UPDATE_START = 'USER_ROLE_UPDATE_START';
export const USER_ROLE_UPDATE_SUCCESS = 'USER_ROLE_UPDATE_SUCCESS';
export const USER_ROLE_UPDATE_FAILURE = 'USER_ROLE_UPDATE_FAILURE';

export const PROPERTY_CASEINSTANCE_BY_PROPERTY_ID_START =
  'PROPERTY_CASEINSTANCE_BY_PROPERTY_ID_START';
export const PROPERTY_CASEINSTANCE_BY_PROPERTY_ID_SUCCESS =
  'PROPERTY_CASEINSTANCE_BY_PROPERTY_ID_SUCCESS';

export const PROPERTY_DOCUMENT_UPLOAD_FORM = 'PROPERTY_DOCUMENT_UPLOAD_FORM';
export const PROPERTY_DOCUMENT_PREVIEW_FORM = 'PROPERTY_DOCUMENT_PREVIEW_FORM';
export const PROPERTY_DOCUMENT_UPLOAD_FORM_SUCCESS =
  'PROPERTY_DOCUMENT_UPLOAD_FORM_SUCCESS';
export const PROPERTY_DOCUMENT_PREVIEW_FORM_SUCCESS =
  'PROPERTY_DOCUMENT_PREVIEW_FORM_SUCCESS';
export const PROPERTY_DOCUMENT_PREVIEW_FILE_DATA =
  'PROPERTY_DOCUMENT_PREVIEW_FILE_DATA';
export const PROPERTY_DOCUMENT_PREVIEW_FILE_DATA_SUCCESS =
  'PROPERTY_DOCUMENT_PREVIEW_FILE_DATA_SUCCESS';
export const PROPERTY_FILE_CATEGORY_TYPE = 'PROPERTY_FILE_CATEGORY_TYPE';
export const RESET_PREVIEW_FILE_DATA = 'RESET_PREVIEW_FILE_DATA';

export const INITIATE_OPEN_TASK_COUNT = 'INITIATE_OPEN_TASK_COUNT';
export const GET_OPEN_TASK_COUNT = 'GET_OPEN_TASK_COUNT';
export const INITIATE_COMPLETED_TASK_COUNT = 'INITIATE_COMPLETED_TASK_COUNT';
export const GET_COMPLETED_TASK_COUNT = 'GET_COMPLETED_TASK_COUNT';
export const INITIATE_TEAM_OPEN_TASK_COUNT = 'INITIATE_OPEN_TASK_COUNT';
export const GET_TEAM_OPEN_TASK_COUNT = 'GET_TEAM_OPEN_TASK_COUNT';
export const INITIATE_TEAM_COMPLETED_TASK_COUNT =
  'INITIATE_COMPLETED_TASK_COUNT';
export const GET_TEAM_COMPLETED_TASK_COUNT = 'GET_COMPLETED_TASK_COUNT';

export const PROPERTY_STRATEGY_SAVINGS_FORM_START =
  'PROPERTY_STRATEGY_SAVINGS_FORM_START';
export const PROPERTY_STRATEGY_SAVINGS_FORM_SUCCESS =
  'PROPERTY_STRATEGY_SAVINGS_FORM_SUCCESS';
export const PROPERTY_STRATEGY_CLAIMS_FORM_START =
  'PROPERTY_STRATEGY_CLAIMS_FORM_START';
export const PROPERTY_STRATEGY_CLAIMS_FORM_SUCCESS =
  'PROPERTY_STRATEGY_CLAIMS_FORM_SUCCESS';
export const PROPERTY_STRATEGY_ACTUALS_FORM_START =
  'PROPERTY_STRATEGY_ACTUALS_FORM_START';
export const PROPERTY_STRATEGY_ACTUALS_FORM_SUCCESS =
  'PROPERTY_STRATEGY_ACTUALS_FORM_SUCCESS';
export const PROPERTY_STRATEGY_CONVEYANCE_FORM_START =
  'PROPERTY_STRATEGY_CONVEYANCE_FORM_START';
export const PROPERTY_STRATEGY_CONVEYANCE_FORM_SUCCESS =
  'PROPERTY_STRATEGY_CONVEYANCE_FORM_SUCCESS';
export const PROPERTY_STRATEGY_CWCOT_FORM_START =
  'PROPERTY_STRATEGY_CWCOT_FORM_START';
export const PROPERTY_STRATEGY_CWCOT_FORM_SUCCESS =
  'PROPERTY_STRATEGY_CWCOT_FORM_SUCCESS';
export const PROPERTY_STRATEGY_REO_ASIS_FORM_START =
  'PROPERTY_STRATEGY_REO_ASIS_FORM_START';
export const PROPERTY_STRATEGY_REO_ASIS_FORM_SUCCESS =
  'PROPERTY_STRATEGY_REO_ASIS_FORM_SUCCESS';
export const PROPERTY_STRATEGY_REO_REPAIR_FORM_START =
  'PROPERTY_STRATEGY_REO_REPAIR_FORM_START';
export const PROPERTY_STRATEGY_REO_REPAIR_FORM_SUCCESS =
  'PROPERTY_STRATEGY_REO_REPAIR_FORM_SUCCESS';

export const PROPERTY_PROJECTIONS_GET_START = 'PROPERTY_PROJECTIONS_GET_START';
export const PROPERTY_PROJECTIONS_GET_SUCCESS =
  'PROPERTY_PROJECTIONS_GET_SUCCESS';
export const PROPERTY_PROJECTIONS_ADD_START = 'PROPERTY_PROJECTIONS_ADD_START';
export const PROPERTY_PROJECTIONS_ADD_SUCCESS =
  'PROPERTY_PROJECTIONS_ADD_SUCCESS';
export const PROPERTY_PROJECTIONS_UPDATE_START =
  'PROPERTY_PROJECTIONS_UPDATE_START';
export const PROPERTY_PROJECTIONS_UPDATE_SUCCESS =
  'PROPERTY_PROJECTIONS_UPDATE_SUCCESS';
export const PROPERTY_PROJECTIONS_FLW_BINDING_DATA =
  'PROPERTY_PROJECTIONS_FLW_BINDING_DATA';
export const PROPERTY_PROJECTIONS_GLD_FORM_DATA =
  'PROPERTY_PROJECTIONS_GLD_FORM_DATA';
export const PROPERTY_PROJECTIONS_DATA_RESET =
  'PROPERTY_PROJECTIONS_DATA_RESET';

export const INITIATE_OFFER_COUNT = 'INITIATE_OFFER_COUNT';
export const GET_OFFER_COUNT = 'GET_OFFER_COUNT';

export const PROPERTY_PROJECTIONS_LIST_GET_START =
  'PROPERTY_PROJECTIONS_LIST_GET_START';
export const PROPERTY_PROJECTIONS_LIST_GET_SUCCESS =
  'PROPERTY_PROJECTIONS_LIST_GET_SUCCESS';
export const PROPERTY_PROJECTIONS_SET_HISTORY =
  'PROPERTY_PROJECTIONS_SET_HISTORY';

export const PROPERTY_STRATEGY_BASELINE_FORM_START =
  'PROPERTY_STRATEGY_BASELINE_FORM_START';
export const PROPERTY_STRATEGY_BASELINE_FORM_SUCCESS =
  'PROPERTY_STRATEGY_BASELINE_FORM_SUCCESS';

export const PROPERTY_TEMPLATE_LISTING_START =
  'PROPERTY_TEMPLATE_LISTING_START';
export const PROPERTY_TEMPLATE_LISTING_SUCCESS =
  'PROPERTY_TEMPLATE_LISTING_SUCCESS';
export const PROPERTY_TEMPLATE_UPLOAD_START = 'PROPERTY_TEMPLATE_UPLOAD_START';
export const PROPERTY_TEMPLATE_UPLOAD_SUCCESS =
  'PROPERTY_TEMPLATE_UPLOAD_SUCCESS';
export const PROPERTY_TEMPLATE_DOWNLOAD_START =
  'PROPERTY_TEMPLATE_DOWNLOAD_START';
export const PROPERTY_TEMPLATE_DOWNLOAD_SUCCESS =
  'PROPERTY_TEMPLATE_DOWNLOAD_SUCCESS';
export const PROPERTY_GET_ERROR_FILE_DETAILS_START =
  'PROPERTY_GET_ERROR_FILE_DETAILS_START';
export const PROPERTY_GET_ERROR_FILE_DETAILS_SUCCESS =
  'PROPERTY_GET_ERROR_FILE_DETAILS_SUCCESS';
export const PROPERTY_TEMPLATE_LIST_REFRESH = 'PROPERTY_TEMPLATE_LIST_REFRESH';

export const PROPERTY_GET_LEGACY_DETAILS = 'PROPERTY_GET_LEGACY_DETAILS';
export const PROPERTY_GET_BACK_LEGACY_DETAILS =
  'PROPERTY_GET_BACK_LEGACY_DETAILS';
export const PROPERTY_GET_LEGACY_MESSAGES_START =
  'PROPERTY_GET_LEGACY_MESSAGES_START';
export const PROPERTY_GET_LEGACY_MESSAGES_SUCCESS =
  'PROPERTY_GET_LEGACY_MESSAGES_SUCCESS';

export const PROPERTY_ROLES_FORMDEFIINITION = 'PROPERTY_ROLES_FORMDEFIINITION';
export const PROPERTY_FLOWABLE_FORMDEF = 'PROPERTY_FLOWABLE_FORMDEF';
export const PROPERTY_RULES_FORMDEFIINITION = 'PROPERTY_RULES_FORMDEFIINITION';

export const GET_FILES_S3_START = 'GET_FILES_S3_START';
export const GET_FILES_S3_SUCCESS = 'GET_FILES_S3_SUCCESS';


export const PROPERTY_GET_ALL_PROCESS_INSTANCES =
  'PROPERTY_GET_ALL_PROCESS_INSTANCES';
export const PROPERTY_GET_ALL_PROCESS_INSTANCES_SUCCESS =
  'PROPERTY_GET_ALL_PROCESS_INSTANCES_SUCCESS';
