export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';

export const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SET_INITIAL_USER_PROFILE_SETTINGS =
  'SET_INITIAL_USER_PROFILE_SETTINGS';
export const GET_USER_DATA = '[USER] GET_USER_DATA';
export const SET_USER_DATA = '[USER] SET DATA';
export const REMOVE_USER_DATA = '[USER] REMOVE DATA';
export const USER_LOGGED_OUT = '[USER] LOGGED OUT';
export const USER_CHANGE_TENANT = 'USER_CHANGE_TENANT';
export const DASHBOARD_CURRENT_TENANT_START = 'DASHBOARD_CURRENT_TENANT_START';
export const DASHBOARD_CURRENT_TENANT_SUCCESS =
  'DASHBOARD_CURRENT_TENANT_SUCCESS';
export const DASHBOARD_SET_SELECTED_RESOURCE_START =
  'DASHBOARD_SET_SELECTED_RESOURCE_START';
export const DASHBOARD_SET_SELECTED_RESOURCE_SUCCESS =
  'DASHBOARD_SET_SELECTED_RESOURCE_SUCCESS';
export const USER_INVALID_SESSION = 'USER_INVALID_SESSION';

export const USER_SET_COOKIES = 'USER_SET_COOKIES';
export const USER_SET_COOKIES_SUCCESS = 'USER_SET_COOKIES_SUCCESS';
export const USER_SELECTED_TENANT = 'USER_SELECTED_TENANT';

export const DATASTUDIO_REDIRECT_START = 'DATASTUDIO_REDIRECT_START';
export const DATASTUDIO_REDIRECT_SUCCESS = 'DATASTUDIO_REDIRECT_SUCCESS';
export const DATASTUDIO_REDIRECT_FAILURE = 'DATASTUDIO_REDIRECT_FAILURE';

export const GLOBAL_COOKIES_SET = 'GLOBAL_COOKIES_SET';
export const SET_TENANT_FROM_VENDOR_AGENT_TASK =
  'SET_TENANT_FROM_VENDOR_AGENT_TASK';
