export const REQUEST_OPEN_CLAIM_TASK_PAYLOAD =
  '[TASK MNGT] REQUEST_OPEN_CLAIM_TASK_PAYLOAD';
export const FETCH_OPEN_CLAIM_TASK_PAYLOAD =
  '[TASK MNGT] FETCH_OPEN_CLAIM_TASK_PAYLOAD';

export const REQUEST_CLOSE_CLAIM_TASK_PAYLOAD =
  '[TASK MNGT] REQUEST_CLOSE_CLAIM_TASK_PAYLOAD';
export const FETCH_CLOSE_TEAM_TASK_PAYLOAD =
  '[TASK MNGT] FETCH_CLOSE_TEAM_TASK_PAYLOAD';

export const PROCESS_TASK_CLAIM = '[TASK MNGT] PROCESS_TASK_CLAIM';
export const PROCESS_TASK_CLAIM_SUCCESS =
  '[TASK MNGT] PROCESS_TASK_CLAIM_SUCCESS';

export const REQUEST_OPEN_ASSIGN_TASK_PAYLOAD =
  '[TASK MNGT] REQUEST_OPEN_ASSIGN_TASK_PAYLOAD';
export const REQUEST_CLOSE_ASSIGN_TASK_PAYLOAD =
  '[TASK MNGT] REQUEST_CLOSE_ASSIGN_TASK_PAYLOAD';

export const FETCH_OPEN_ASSIGN_TASK_PAYLOAD =
  '[TASK MNGT] FETCH_OPEN_ASSIGN_TASK_PAYLOAD';
export const FETCH_CLOSE_ASSIGN_TASK_PAYLOAD =
  '[TASK MNGT] FETCH_CLOSE_ASSIGN_TASK_PAYLOAD';

export const REQUEST_TASK_DETAIL_FORM_BY_TASKID =
  '[TASK MNGT] REQUEST_TASK_DETAIL_FORM_BY_TASKID';
export const FETCH_TASK_DETAIL_FORM_BY_TASKID =
  '[TASK MNGT] FETCH_TASK_DETAIL_FORM_BY_TASKID';

export const RESET_TASK_DETAILS = '[TASK MNGT] RESET_TASK_DETAILS';
export const SHOW_TASK_BUTTONS = 'SHOW_TASK_BUTTONS';
export const RESET_TASK_BUTTONS = 'RESET_TASK_BUTTONS';
export const SHOW_TASK_DETAILS = '[TASK MNGT] SHOW_TASK_DEATAILS';

export const TASKMANAGMENT_FORMDEFIINITION =
  '[TASK MNGT] FORMDEFNITION_OPEN_CLAIMS';

export const POST_ADHOC_PROCESS = '[TASK MNGT] POST_ADHOC_PROCESS';
export const CLAIMS_TASK_REASSIGN_START =
  '[TASK MNGT] CLAIMS_TASK_REASSIGN_START';
export const CLAIMS_TASK_REASSIGN_SUCCESS =
  '[TASK MNGT] CLAIMS_TASK_REASSIGN_SUCCESS';

export const OPEN_TASK_REFRESH = '[TASK MNGT] OPEN_TASK_REFRESH';
