export const GET_API_SERVICES_START='GET_API_SERVICES_START';
export const GET_API_SERVICES_SUCCESS='GET_API_SERVICES_SUCCESS';

export const GET_API_SERVICES_LOADING='GET_API_SERVICES_LOADING';
export const GET_BODY_VALUE_SUCCESS='GET_BODY_VALUE_SUCCESS';

export const GET_DATA_INTEGRATION_DATA_START='GET_DATA_INTEGRATION_DATA_START';
export const GET_DATA_INTEGRATION_DATA_SUCCESS='GET_DATA_INTEGRATION_DATA_SUCCESS';