export const NAVIGATION_RESOURCE_START = 'NAVIGATION_RESOURCE_START';
export const NAVIGATION_RESOURCE_SUCCESS = 'NAVIGATION_RESOURCE_SUCCESS';
export const USER_CHANGE_TENANT = 'USER_CHANGE_TENANT';
export const DASHBOARD_CURRENT_TENANT_START = 'DASHBOARD_CURRENT_TENANT_START';
export const DASHBOARD_CURRENT_TENANT_SUCCESS =
  'DASHBOARD_CURRENT_TENANT_SUCCESS';
export const DASHBOARD_SET_SELECTED_RESOURCE_START =
  'DASHBOARD_SET_SELECTED_RESOURCE_START';
export const DASHBOARD_SET_SELECTED_RESOURCE_SUCCESS =
  'DASHBOARD_SET_SELECTED_RESOURCE_SUCCESS';
export const CONTEXT_RESOURCE_START = 'CONTEXT_RESOURCE_START';
export const CONTEXT_RESOURCE_SUCCESS = 'CONTEXT_RESOURCE_SUCCESS';
export const CONTEXT_RESOURCE_FAILURE = 'CONTEXT_RESOURCE_FAILURE';

export const EXPLORE_TOUR = '[TOUR] EXPLORE_TOUR';
export const GET_STATE_US = 'GET_STATE_US';
export const GET_STATE_US_SUCCESS = 'GET_STATE_US_SUCCESS';
export const GET_STATE_US_FAILURE = 'GET_STATE_US_FAILURE';

export const GET_DELIVERABLE_MATRIX = 'GET_DELIVERABLE_MATRIX';
export const GET_DELIVERABLE_MATRIX_SUCCESS = 'GET_DELIVERABLE_MATRIX_SUCCESS';
export const GET_DELIVERABLE_MATRIX_FAILURE = 'GET_DELIVERABLE_MATRIX_FAILURE';

export const GET_EVICTION_TYPE = 'GET_EVICTION_TYPE';
export const GET_EVICTION_TYPE_SUCCESS = 'GET_EVICTION_TYPE_SUCCESS';
export const GET_EVICTION_TYPE_FAILURE = 'GET_EVICTION_TYPE_FAILURE';

export const GET_PROPERTY_TYPE = 'GET_PROPERTY_TYPE';
export const GET_PROPERTY_TYPE_SUCCESS = 'GET_PROPERTY_TYPE_SUCCESS';
export const GET_PROPERTY_TYPE_FAILURE = 'GET_PROPERTY_TYPE_FAILURE';

export const GET_TASK_DATA = 'GET_TASK_DATA';
export const GET_TASK_DATA_SUCCESS = 'GET_TASK_DATA_SUCCESS';
export const GET_TASK_DATA_FAILURE = 'GET_TASK_DATA_FAILURE';

export const GET_AGENT_TYPE = 'GET_AGENT_TYPE';
export const GET_AGENT_TYPE_SUCCESS = 'GET_AGENT_TYPE_SUCCESS';
export const GET_AGENT_TYPE_FAILURE = 'GET_AGENT_TYPE_FAILURE';

export const DOWNLOAD_FILE_START = 'DOWNLOAD_FILE_START';
export const DOWNLOAD_FILE_SUCCESS = 'DOWNLOAD_FILE_SUCCESS';
export const CHECK_TEMPLATE_START = 'CHECK_TEMPLATE_START';
export const CHECK_TEMPLATE_SUCCESS = 'CHECK_TEMPLATE_SUCCESS';
export const GENERATE_FILE_START = 'GENERATE_FILE_START';
export const GENERATE_FILE_SUCCESS = 'GENERATE_FILE_SUCCESS';
export const SET_FILE_URL_START = 'SET_FILE_URL_START';
export const SET_FILE_URL_SUCCESS = 'SET_FILE_URL_SUCCESS';
export const RESET_FILE_UTILITY = 'RESET_FILE_UTILITY';

export const DOCUMENTS_LIST_START = 'DOCUMENTS_LIST_START';
export const DOCUMENTS_LIST_SUCCESS = 'DOCUMENTS_LIST_SUCCESS';
export const DOCUMENTS_DELETE_START = 'DOCUMENTS_DELETE_START';
export const DOCUMENTS_DELETE_SUCCESS = 'DOCUMENTS_DELETE_SUCCESS';

export const COMMON_FORMDEFIINITION = 'COMMON_FORMDEFIINITION';

export const FLOWABLE_FORM_DATA_TABLE_ROW_SELECTED_DATA =
  'FLOWABLE_FORM_DATA_TABLE_ROW_SELECTED_DATA';
export const GET_FLOWABLE_FORM_DATA_START = 'GET_FLOWABLE_FORM_DATA_START';
export const GET_CHANGELOG_FIELD_LEVEL_START =
  'GET_CHANGELOG_FIELD_LEVEL_START';
export const GET_CHANGELOG_FIELD_LEVEL_SUCCESS =
  'GET_CHANGELOG_FIELD_LEVEL_SUCCESS';

export const REQUEST_CHANGE_LOG_PAYLOAD_START='REQUEST_CHANGE_LOG_PAYLOAD_START';
export const REQUEST_CHANGE_LOG_PAYLOAD_SUCCESS='REQUEST_CHANGE_LOG_PAYLOAD_SUCCESS';
