export const FLOWABLE_CONTROL_LOGIN = 'FLOWABLE_CONTROL_LOGIN';
export const FLOWABLE_CONTROL_LOGIN_SUCCESS = 'FLOWABLE_CONTROL_LOGIN_SUCCESS';
export const FLOWABLE_CONTROL_LOGIN_FAILED = 'FLOWABLE_CONTROL_LOGIN_FAILED';
