export const GET_OFFER_DETAILS = 'GET_OFFER_DETAILS';
export const SAVE_OFFER_DETAILS = 'SAVE_OFFER_DETAILS';
export const UPDATE_OFFER_DETAILS = 'UPDATE_OFFER_DETAILS';
export const GET_OFFER_DETAILS_START = 'GET_OFFER_DETAILS_START';
export const SAVE_OFFER_DETAILS_START = 'SAVE_OFFER_DETAILS_START';
export const UPDATE_OFFER_DETAILS_START = 'UPDATE_OFFER_DETAILS_START';
export const UPDATE_OFFER_DETAILS_SUCCESS = 'UPDATE_OFFER_DETAILS_SUCCESS';
export const UPDATE_OFFER_DETAILS_FAILURE = 'UPDATE_OFFER_DETAILS_FAILURE';

export const GET_PROPERTY_OFFER_LIST = 'GET_PROPERTY_OFFER_LIST';
export const GET_OFFER_STATUS = 'GET_OFFER_STATUS';
export const GET_PROPERTY_OFFER_LIST_START = 'GET_PROPERTY_OFFER_LIST_START';
export const GET_OFFER_STATUS_START = 'GET_OFFER_STATUS_START';

export const OFFER_LISTING_FORM_FETCH_START = 'OFFER_LISTING_FORM_FETCH_START';
export const OFFER_LISTING_FORM_FETCH_SUCCESS =
  'OFFER_LISTING_FORM_FETCH_SUCCESS';
export const OFFER_LISTING_FORM_FETCH_FAILURE =
  'OFFER_LISTING_FORM_FETCH_FAILURE';

export const FILTER_PROPERTY_OFFER_LIST_START =
  'FILTER_PROPERTY_OFFER_LIST_START';
export const FILTER_PROPERTY_OFFER_LIST_SUCCESS =
  'FILTER_PROPERTY_OFFER_LIST_SUCCESS';
export const FILTER_PROPERTY_OFFER_LIST_FAILURE =
  'FILTER_PROPERTY_OFFER_LIST_FAILURE';

export const PROPERTY_OFFER_LIST_VIEW_TYPE_START =
  'PROPERTY_OFFER_LIST_VIEW_TYPE_START';
export const PROPERTY_OFFER_LIST_VIEW_TYPE_SUCCESS =
  'PROPERTY_OFFER_LIST_VIEW_TYPE_SUCCESS';
export const PROPERTY_OFFER_LIST_VIEW_TYPE_FAILURE =
  'PROPERTY_OFFER_LIST_VIEW_TYPE_FAILURE';

export const PROPERTY_OFFER_DETAILS_CURRENT_TAB_START =
  'PROPERTY_OFFER_DETAILS_CURRENT_TAB_START';
export const PROPERTY_OFFER_DETAILS_CURRENT_TAB_SUCCESS =
  'PROPERTY_OFFER_DETAILS_CURRENT_TAB_SUCCESS';
export const PROPERTY_OFFER_DETAILS_CURRENT_TAB_FAILURE =
  'PROPERTY_OFFER_DETAILS_CURRENT_TAB_FAILURE';

export const EDIT_OFFER_FORM_FETCH_START = 'EDIT_OFFER_FORM_FETCH_START';
export const EDIT_OFFER_FORM_FETCH_COMPLETED_SUCCESS =
  'EDIT_OFFER_FORM_FETCH_COMPLETED_SUCCESS';
export const EDIT_OFFER_FORM_FETCH_SUCCESS = 'EDIT_OFFER_FORM_FETCH_SUCCESS';
export const EDIT_OFFER_FORM_FETCH_FAILURE = 'EDIT_OFFER_FORM_FETCH_FAILURE';
export const EDIT_OFFER_FORM_FETCH_RESET_START =
  'EDIT_OFFER_FORM_FETCH_RESET_START';
export const EDIT_OFFER_FORM_FETCH_RESET_SUCCESS =
  'EDIT_OFFER_FORM_FETCH_RESET_SUCCESS';

export const GET_PROPERTY_OFFER_LIST_WITH_VERSION_START =
  'GET_PROPERTY_OFFER_LIST_WITH_VERSION_START';
export const GET_PROPERTY_OFFER_LIST_WITH_VERSION_SUCCESS =
  'GET_PROPERTY_OFFER_LIST_WITH_VERSION_SUCCESS';
export const GET_PROPERTY_OFFER_LIST_WITH_VERSION_FAILURE =
  'GET_PROPERTY_OFFER_LIST_WITH_VERSION_FAILURE';

export const OFFER_CONTACTS_FETCH_START = 'OFFER_CONTACTS_FETCH_START';
export const OFFER_CONTACTS_FETCH_SUCCESS = 'OFFER_CONTACTS_FETCH_SUCCESS';
export const OFFER_CONTACTS_FETCH_FAILURE = 'OFFER_CONTACTS_FETCH_FAILURE';

export const GET_OFFER_WORKSHEET_DATA_START = 'GET_OFFER_WORKSHEET_DATA_START';
export const GET_OFFER_WORKSHEET_DATA_SUCCESS =
  'GET_OFFER_WORKSHEET_DATA_SUCCESS';
export const GET_OFFER_WORKSHEET_DATA_FAILURE =
  'GET_OFFER_WORKSHEET_DATA_FAILURE';

export const GET_OFFER_COUNT_START = 'GET_OFFER_COUNT_START';
export const GET_OFFER_COUNT_SUCCESS = 'GET_OFFER_COUNT_SUCCESS';

export const GET_OFFER_MAIL_PAYLOAD_START = 'GET_OFFER_MAIL_PAYLOAD_START';
export const GET_OFFER_MAIL_PAYLOAD_SUCCESS = 'GET_OFFER_MAIL_PAYLOAD_SUCCESS';
export const GET_OFFER_MAIL_PAYLOAD_RESET = 'GET_OFFER_MAIL_PAYLOAD_RESET';

export const SHOW_SEND_WORK_SHEET_POPUP = 'SHOW_SEND_WORK_SHEET_POPUP';
export const HIDE_SEND_WORK_SHEET_POPUP = 'HIDE_SEND_WORK_SHEET_POPUP';
export const OFFERS_FORMDEFIINITION = '[OFFERS] OFFERS_FORMDEFIINITION';