export const FETCH_DECISION_TABLE = 'FETCH_DECISION_TABLE';
export const FETCH_DECISION_TABLE_SUCCESS = 'FETCH_DECISION_TABLE_SUCCESS';
export const FETCH_DECISION_TABLE_FAILURE = 'FETCH_DECISION_TABLE_FAILURE';
export const FETCH_RULE_GROUP = 'FETCH_RULE_GROUP';
export const FETCH_RULE_GROUP_SUCCESS = 'FETCH_RULE_GROUP_SUCCESS';
export const FETCH_RULE_GROUP_FAILURE = 'FETCH_RULE_GROUP_FAILURE';

export const UPDATE_DECISION_TABLE = 'UPDATE_DECISION_TABLE';
export const UPDATE_DECISION_TABLE_SUCCESS = 'UPDATE_DECISION_TABLE_SUCCESS';
export const UPDATE_DECISION_TABLE_FAILURE = 'UPDATE_DECISION_TABLE_FAILURE';

export const GET_RULE_DATA_FOR_MODIFICATOIN = 'GET_RULE_DATA_FOR_MODIFICATOIN';

export const FETCH_INVESTOR_GROUP = 'FETCH_INVESTOR_GROUP';
export const FETCH_INVESTOR_GROUP_SUCCESS = 'FETCH_INVESTOR_GROUP_SUCCESS';
export const FETCH_INVESTOR_GROUP_FAILURE = 'FETCH_INVESTOR_GROUP_FAILURE';

export const FETCH_LEGAL_ENTITY_FORM_START = 'FETCH_LEGAL_ENTITY_FORM_START';
export const FETCH_LEGAL_ENTITY_FORM_SUCCESS =
  'FETCH_LEGAL_ENTITY_FORM_SUCCESS';
export const FETCH_LEGAL_ENTITY_FORM_FAILURE =
  'FETCH_LEGAL_ENTITY_FORM_FAILURE';

export const SERACH_INVESTOR_GROUPS = 'SERACH_INVESTOR_GROUPS';
export const SERACH_INVESTOR_GROUPS_SUCCESS = 'SERACH_INVESTOR_GROUPS_SUCCESS';
export const SERACH_INVESTOR_GROUPS_FAILURE = 'SERACH_INVESTOR_GROUPS_FAILURE';

export const SAVE_INVESTOR_TO_GROUP = 'SAVE_INVESTOR_TO_GROUP';
export const SAVE_INVESTOR_TO_GROUP_SUCCESS = 'SAVE_INVESTOR_TO_GROUP_SUCCESS';
export const SAVE_INVESTOR_TO_GROUP_FAILURE = 'SAVE_INVESTOR_TO_GROUP_FAILURE';

export const CREATE_INVESTOR_GROUP = 'CREATE_INVESTOR_GROUP';
export const CREATE_INVESTOR_GROUP_SUCCESS = 'CREATE_INVESTOR_GROUP_SUCCESS';
export const CREATE_INVESTOR_GROUP_FAILURE = 'CREATE_INVESTOR_GROUP_FAILURE';

export const DELETE_INVESTOR_GROUP_BY_ID = 'DELETE_INVESTOR_GROUP_BY_ID';
export const DELETE_INVESTOR_GROUP_BY_ID_SUCCESS =
  'DELETE_INVESTOR_GROUP_BY_ID_SUCCESS';
export const DELETE_INVESTOR_GROUP_BY_ID_FAILURE =
  'DELETE_INVESTOR_GROUP_BY_ID_FAILURE';

export const FETCH_UNASSIGNED_INVESTOR = 'FETCH_UNASSIGNED_INVESTOR';
export const FETCH_UNASSIGNED_INVESTOR_SUCCESS =
  'FETCH_UNASSIGNED_INVESTOR_SUCCESS';

export const FETCH_FORM_INVESTOR_TO_GROUP = 'FETCH_FORM_INVESTOR_TO_GROUP';
export const FETCH_FORM_INVESTOR_TO_GROUP_SUCCESS =
  'FETCH_FORM_INVESTOR_TO_GROUP_SUCCESS';
export const FETCH_FORM_INVESTOR_TO_GROUP_FAILURE =
  'FETCH_FORM_INVESTOR_TO_GROUP_FAILURE';

export const FETCH_FORM_INVESTOR_GROUP_CREATION =
  'FETCH_FORM_INVESTOR_GROUP_CREATION';
export const FETCH_FORM_INVESTOR_GROUP_CREATION_SUCCESS =
  'FETCH_FORM_INVESTOR_GROUP_CREATION_SUCCESS';
export const FETCH_FORM_INVESTOR_GROUP_CREATION_FAILURE =
  'FETCH_FORM_INVESTOR_GROUP_CREATION_FAILURE';

export const PROCESS_MANAGE_PRODUCT_FORM = 'PROCESS_MANAGE_PRODUCT_FORM';
export const FETCH_MANAGE_PRODUCT_FORM = 'FETCH_MANAGE_PRODUCT_FORM';
export const POST_MANAGE_PRODUCT_DATA = 'POST_MANAGE_PRODUCT_DATA';
export const PROCESS_MANAGE_PRODUCT_FORM_SUCCESS =
  'PROCESS_MANAGE_PRODUCT_FORM_SUCCESS';
export const FETCH_MANAGE_PRODUCT_LIST = 'FETCH_MANAGE_PRODUCT_LIST';
export const FETCH_MANAGE_PRODUCT_LIST_SUCCESS =
  'FETCH_MANAGE_PRODUCT_LIST_SUCCESS';
export const FETCH_PRODUCT_CATEGORY_DATA = 'FETCH_PRODUCT_CATEGORY_DATA';
export const FETCH_MANAGE_PRODUCT_LIST_CLEAR =
  'FETCH_MANAGE_PRODUCT_LIST_CLEAR';
export const DELETE_APPROVED_PRODUCT = 'DELETE_APPROVED_PRODUCT';
export const CLOSE_MODEL = 'CLOSE_MODEL';

export const FETCH_VENDOR_LIST_BY_PRODUCT_CLEAR =
  'FETCH_VENDOR_LIST_BY_PRODUCT_CLEAR';
export const FETCH_VENDOR_LIST_BY_PRODUCT = 'FETCH_VENDOR_LIST_BY_PRODUCT';

export const FETCH_MANAGE_CLIENT_CONFIG_FORM_START =
  'FETCH_MANAGE_CLIENT_CONFIG_FORM_START';
export const FETCH_MANAGE_CLIENT_CONFIG_FORM_SUCCESS =
  'FETCH_MANAGE_CLIENT_CONFIG_FORM_SUCCESS';
export const FETCH_MANAGE_CLIENT_CONFIG_FORM_FAILURE =
  'FETCH_MANAGE_CLIENT_CONFIG_FORM_FAILURE';

export const FETCH_MANAGE_WORKFLOW_SETTINGS_FORM_START =
  'FETCH_MANAGE_WORKFLOW_SETTINGS_FORM_START';
export const FETCH_MANAGE_WORKFLOW_SETTINGS_FORM_SUCCESS =
  'FETCH_MANAGE_WORKFLOW_SETTINGS_FORM_SUCCESS';
export const FETCH_MANAGE_WORKFLOW_SETTINGS_FORM_FAILURE =
  'FETCH_MANAGE_WORKFLOW_SETTINGS_FORM_FAILURE';

export const FETCH_USER_LOAD_BALANCE_FORM_START =
  'FETCH_USER_LOAD_BALANCE_FORM_START';
export const FETCH_USER_LOAD_BALANCE_FORM_SUCCESS =
  'FETCH_USER_LOAD_BALANCE_FORM_SUCCESS';
export const FETCH_USER_LOAD_BALANCE_FORM_FAILURE =
  'FETCH_USER_LOAD_BALANCE_FORM_FAILURE';

export const FETCH_STATE_ROLE_ASSIGN_FORM_START =
  'FETCH_STATE_ROLE_ASSIGN_FORM_START';
export const FETCH_STATE_ROLE_ASSIGN_FORM_SUCCESS =
  'FETCH_STATE_ROLE_ASSIGN_FORM_SUCCESS';
export const FETCH_STATE_ROLE_ASSIGN_FORM_FAILURE =
  'FETCH_STATE_ROLE_ASSIGN_FORM_FAILURE';

export const FETCH_FORM_INVESTOR_GROUP_LIST =
  '[FLOWABLE] FETCH_FORM_INVESTOR_GROUP_LIST';
export const FETCH_FORM_INVESTOR_GROUP_LIST_SUCCESS =
  '[FLOWABLE] FETCH_FORM_INVESTOR_GROUP_LIST_SUCCESS';
export const FETCH_FORM_INVESTOR_GROUP_LIST_FAILURE =
  '[FLOWABLE] FETCH_FORM_INVESTOR_GROUP_LIST_FAILURE';

export const PROCESS_VENDOR_APPROVAL = 'PROCESS_VENDOR_APPROVAL';
export const FETCH_VENDOR_LIST_BY_PRODUCT_SUCCESS =
  'FETCH_VENDOR_LIST_BY_PRODUCT_SUCCESS';
export const FIND_INVESTOR_BY_INVESTOR_GROUP =
  'FIND_INVESTOR_BY_INVESTOR_GROUP';
export const FIND_INVESTOR_BY_INVESTOR_GROUP_SUCCESS =
  'FIND_INVESTOR_BY_INVESTOR_GROUP_SUCCESS';
export const FIND_INVESTOR_BY_INVESTOR_GROUP_FAILURE =
  'FIND_INVESTOR_BY_INVESTOR_GROUP_FAILURE';
export const INVESTOR_REFRESH = 'INVESTOR_REFRESH';
export const UPDATE_INVESTOR_GROUP = 'UPDATE_INVESTOR_GROUP';
export const UPDATE_INVESTOR_GROUP_SUCCESS = 'UPDATE_INVESTOR_GROUP_SUCCESS';
export const UPDATE_INVESTOR_GROUP_FAILURE = 'UPDATE_INVESTOR_GROUP_FAILURE';

export const CREATE_RULE_FOR_ID = 'CREATE_RULE_FOR_ID';
export const CREATE_RULE_FOR_ID_SUCCESS = 'CREATE_RULE_FOR_ID_SUCCESS';
export const CREATE_RULE_FOR_ID_FAILURE = 'CREATE_RULE_FOR_ID_FAILURE';

export const FETCH_FORM_INVESTOR_LIST = '[FLOWABLE] FETCH_FORM_INVESTOR_LIST';
export const FETCH_FORM_INVESTOR_LIST_SUCCESS =
  '[FLOWABLE] FETCH_FORM_INVESTOR_LIST_SUCCESS';
export const FETCH_FORM_INVESTOR_LIST_FAILURE =
  '[FLOWABLE] FETCH_FORM_INVESTOR_LIST_FAILURE';

export const FETCH_FLOWABLE_CASE_ID = 'FETCH_FLOWABLE_CASE_ID';
export const FETCH_FLOWABLE_CASE_ID_SUCCESS = 'FETCH_FLOWABLE_CASE_ID_SUCCESS';
export const FETCH_FLOWABLE_CASE_ID_FAILURE = 'FETCH_FLOWABLE_CASE_ID_FAILURE';

export const FETCH_FLOWABLE_PROCESS_ID = 'FETCH_FLOWABLE_PROCESS_ID';
export const FETCH_FLOWABLE_PROCESS_ID_SUCCESS =
  'FETCH_FLOWABLE_PROCESS_ID_SUCCESS';
export const FETCH_FLOWABLE_PROCESS_ID_FAILURE =
  'FETCH_FLOWABLE_PROCESS_ID_FAILURE';

export const SAVE_TO_FLOWABLE = 'SAVE_TO_FLOWABLE';
export const SAVE_TO_FLOWABLE_SUCCESS = 'SAVE_TO_FLOWABLE_SUCCESS';
export const SAVE_TO_FLOWABLE_FAILURE = 'SAVE_TO_FLOWABLE_FAILURE';

export const UPDATE_IN_FLOWABLE = 'UPDATE_IN_FLOWABLE';
export const UPDATE_IN_FLOWABLE_SUCCESS = 'UPDATE_IN_FLOWABLE_SUCCESS';
export const UPDATE_IN_FLOWABLE_FAILURE = 'UPDATE_IN_FLOWABLE_FAILURE';

export const GET_CASE_DATA = 'GET_CASE_DATA';
export const GET_CASE_DATA_SUCCESS = 'GET_CASE_DATA_SUCCESS';
export const GET_CASE_DATA_FAILURE = 'GET_CASE_DATA_FAILURE';

export const ADD_LEGAL_ENTITY = 'ADD_LEGAL_ENTITY';
export const ADD_LEGAL_ENTITY_SUCCESS = 'ADD_LEGAL_ENTITY_SUCCESS';
export const ADD_LEGAL_ENTITY_FAILURE = 'ADD_LEGAL_ENTITY_FAILURE';

export const GET_LEGAL_ENTITY = 'GET_LEGAL_ENTITY';
export const GET_LEGAL_ENTITY_SUCCESS = 'GET_LEGAL_ENTITY_SUCCESS';
export const GET_LEGAL_ENTITY_FAILURE = 'GET_LEGAL_ENTITY_FAILURE';

export const EDIT_LEGAL_ENTITY = 'EDIT_LEGAL_ENTITY';
export const EDIT_LEGAL_ENTITY_SUCCESS = 'EDIT_LEGAL_ENTITY_SUCCESS';
export const EDIT_LEGAL_ENTITY_FAILURE = 'EDIT_LEGAL_ENTITY_FAILURE';

export const DELETE_LEGAL_ENTITY = 'DELETE_LEGAL_ENTITY';
export const DELETE_LEGAL_ENTITY_SUCCESS = 'DELETE_LEGAL_ENTITY_SUCCESS';
export const DELETE_LEGAL_ENTITY_FAILURE = 'DELETE_LEGAL_ENTITY_FAILURE';

export const SAVE_LISTING_TYPE = 'SAVE_LISTING_TYPE';
export const SAVE_LISTING_TYPE_SUCCESS = 'SAVE_LISTING_TYPE_SUCCESS';
export const SAVE_LISTING_TYPE_FAILURE = 'SAVE_LISTING_TYPE_FAILURE';

export const GET_LISTING_TYPE = 'GET_LISTING_TYPE';
export const GET_LISTING_TYPE_SUCCESS = 'GET_LISTING_TYPE_SUCCESS';
export const GET_LISTING_TYPE_FAILURE = 'GET_LISTING_TYPE_FAILURE';

export const EDIT_LISTING_TYPE = 'EDIT_LISTING_TYPE';
export const EDIT_LISTING_TYPE_SUCCESS = 'EDIT_LISTING_TYPE_SUCCESS';
export const EDIT_LISTING_TYPE_FAILURE = 'EDIT_LISTING_TYPE_FAILURE';

export const GET_ALL_DEFAULT_GLOBAL_ROLES_START =
  'GET_ALL_DEFAULT_GLOBAL_ROLES_START';
export const GET_ALL_DEFAULT_GLOBAL_ROLES_SUCCESS =
  'GET_ALL_DEFAULT_GLOBAL_ROLES_SUCCESS';
export const UPDATE_ALL_DEFAULT_GLOBAL_ROLES_START =
  'UPDATE_ALL_DEFAULT_GLOBAL_ROLES_START';
export const UPDATE_ALL_DEFAULT_GLOBAL_ROLES_SUCCESS =
  'UPDATE_ALL_DEFAULT_GLOBAL_ROLES_SUCCESS';
export const UPDATE_DEFAULT_GLOBAL_ROLES_FLAG =
  'UPDATE_DEFAULT_GLOBAL_ROLES_FLAG';
export const GET_ALL_PARTIES_BY_PARTYID_START =
  'GET_ALL_PARTIES_BY_PARTYID_START';
export const GET_ALL_PARTIES_BY_PARTYID_SUCCESS =
  'GET_ALL_PARTIES_BY_PARTYID_SUCCESS';
export const ADD_STATE_ROLE_ASSIGNMENT_START =
  'ADD_STATE_ROLE_ASSIGNMENT_START';
export const ADD_STATE_ROLE_ASSIGNMENT_SUCCESS =
  'ADD_STATE_ROLE_ASSIGNMENT_SUCCESS';
export const GET_STATE_ROLE_ASSIGNMENT_START =
  'GET_STATE_ROLE_ASSIGNMENT_START';
export const GET_STATE_ROLE_ASSIGNMENT_SUCCESS =
  'GET_STATE_ROLE_ASSIGNMENT_SUCCESS';
export const UPDATE_STATE_ROLE_ASSIGNMENT_START =
  'UPDATE_STATE_ROLE_ASSIGNMENT_START';
export const UPDATE_STATE_ROLE_ASSIGNMENT_SUCCESS =
  'UPDATE_STATE_ROLE_ASSIGNMENT_SUCCESS';
export const DELETE_STATE_ROLE_ASSIGNMENT_START =
  'DELETE_STATE_ROLE_ASSIGNMENT_START';
export const DELETE_STATE_ROLE_ASSIGNMENT_SUCCESS =
  'DELETE_STATE_ROLE_ASSIGNMENT_SUCCESS';
export const STATE_ROLE_REFRESH_TABLE = 'STATE_ROLE_REFRESH_TABLE';

export const GET_TEAM_ROLE_START = 'GET_TEAM_ROLE_START';
export const GET_TEAM_ROLE_SUCCESS = 'GET_TEAM_ROLE_SUCCESS';
export const ADD_PARTY_ROLE_TEAM_PARTIES_START =
  'ADD_PARTY_ROLE_TEAM_PARTIES_START';
export const ADD_PARTY_ROLE_TEAM_PARTIES_SUCCESS =
  'ADD_PARTY_ROLE_TEAM_PARTIES_SUCCESS';
export const PARTY_ROLE_TYPE_LISTDATA_CLEAN = 'PARTY_ROLE_TYPE_LISTDATA_CLEAN';
export const ADD_EDIT_ROLE_FORM_DATA = 'ADD_EDIT_ROLE_FORM_DATA';
export const TENANT_ADMIN_TASK_PROPERTIES_EDIT_START =
  'TENANT_ADMIN_TASK_PROPERTIES_EDIT_START';
export const TENANT_ADMIN_TASK_PROPERTIES_EDIT_SUCCESS =
  'TENANT_ADMIN_TASK_PROPERTIES_EDIT_SUCCESS';
export const TENANT_ADMIN_TASK_PROPERTIES_FORM_DATA =
  'TENANT_ADMIN_TASK_PROPERTIES_FORM_DATA';
export const GET_PARTY_ROLE_TYPE_LIST_START = 'GET_PARTY_ROLE_TYPE_LIST_START';
export const GET_PARTY_ROLE_TYPE_LIST_SUCCESS =
  'GET_PARTY_ROLE_TYPE_LIST_SUCCESS';
export const FLOWABLE_TANENT_ADMIN_FORMDEF = 'FLOWABLE_TANENT_ADMIN_FORMDEF';

export const FETCH_DECISION_TABLE_ADMIN = 'FETCH_DECISION_TABLE_ADMIN';
export const FETCH_DECISION_TABLE_ADMIN_SUCCESS =
  'FETCH_DECISION_TABLE_ADMIN_SUCCESS';
export const FETCH_RULES_ADMIN = 'FETCH_RULES_ADMIN';
export const FETCH_RULES_ADMIN_SUCCESS = 'FETCH_RULES_ADMIN_SUCCESS';

export const SERACH_INVESTOR_LIST_START = 'SERACH_INVESTOR_LIST_START';
export const SERACH_INVESTOR_LIST_SUCCESS = 'SERACH_INVESTOR_LIST_SUCCESS';

export const DELETE_STATE_EVITION_BY_ID = '[ADMIN] DELETE_STATE_EVITION_BY_ID';
export const ADD_STATE_EVITION_BY_ID = '[ADMIN] ADD_STATE_EVITION_BY_ID';
export const UPDATE_STATE_EVITION_BY_ID = '[ADMIN] UPDATE_STATE_EVITION_BY_ID';
export const STATE_EVITION_REFRESH = '[ADMIN] STATE_EVITION_REFRESH';

export const CONVERT_TO_VARIABLES = '[ADMIN] CONVERT_TO_VARIABLES';
export const ADMIN_DELETE_STATE_EVICTION_BY_ID = '[ADMIN] ADMIN_DELETE_STATE_EVICTION_BY_ID'
